urlaub/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("zeitplan/", include("zeitplan.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
]

zeitplan/urls.py
from django.urls import path

from . import views

app_name = "zeitplan"
urlpatterns = [
    path("index/", views.index, name="index"),
    # path("overview/", views.OverviewView.as_view(), name="overview"),
    path("overview/", views.overview, name="overview"),
    path("new_day/", views.day_new, name="day_new"),
    path("add_new_day/", views.day_add_new, name="day_add_new"),
    path("<int:day_id>/", views.day_overview, name="day_overview"),
    path("<int:day_id>/delete/", views.day_delete, name="day_delete"),
    path("<int:day_id>/edit/", views.day_edit, name="day_edit"),
    path("<int:day_id>/votes/", views.day_editing, name="day_editing"),
    path("<int:day_id>/new_time_entry/", views.time_entry_add, name="time_entry_add"),
    path("<int:entry_id>/category_add/", views.category_add, name="category_add"),
    path("<int:entry_id>/add_time_frame/", views.add_time_frame, name="add_time_frame"),
]

zeitplan/models.py
from datetime import datetime

from django.contrib.auth.models import User
from django.db import models

from zeitplan.helper_functions import get_german_day_name


class DayManager(models.Manager):
    def create_day(self, day_date: datetime.date, user: User) -> "Day":
        day = self.create(day_date=day_date, user=user)
        day.day_name_german = get_german_day_name(day.day_date)
        day.save()

        return day


class Day(models.Model):
    day_date = models.DateField(null=True, default=None)
    day_name_german = models.CharField(max_length=100, blank=True)
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )

    objects = DayManager()

    @property
    def different_day_date(self) -> str:
        diff_day_date = self.day_date.strftime("%d" "." "%m" "." "%Y")

        return diff_day_date

    def __str__(self) -> str:
        return f"Datum: {self.day_date}"


class EntryCategoryManager(models.Manager):
    def create_entry_category(self, category_text: str) -> "EntryCategory":
        entry_category = self.create(category_text=category_text)

        return entry_category


class EntryCategory(models.Model):
    category_text = models.CharField(max_length=100)

    objects = EntryCategoryManager()

    def __str__(self) -> str:
        return f"Kategorie: {self.category_text}"


class TimeEntryQuerySet(models.QuerySet):
    def time_entry_for_a_day(self, day_id: int) -> "TimeEntryQuerySet":
        time_entry_for_a_day = self.filter(day_id=day_id).order_by("start_of_entry")

        return time_entry_for_a_day


class TimeEntryManager(models.Manager):
    def create_time_entry(self, day: Day, entry_text: str, user: User) -> "TimeEntry":
        time_entry = self.create(day=day, entry_text=entry_text, user=user)

        return time_entry


class TimeEntry(models.Model):
    day = models.ForeignKey(Day, on_delete=models.CASCADE)
    entry_category = models.ForeignKey(
        EntryCategory, models.SET_NULL, blank=True, null=True
    )
    entry_text = models.CharField(max_length=100)
    entry_passed = models.BooleanField(null=True, default=None)
    votes = models.IntegerField(default=0)
    start_of_entry = models.DateTimeField(null=True, default=None)
    end_of_entry = models.DateTimeField(null=True, default=None)
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )

    objects = TimeEntryManager.from_queryset(TimeEntryQuerySet)()

    @property
    def entry_status(self) -> str:
        if self.entry_passed is None:
            entry_status = "Nicht erledigt"
        else:
            entry_status = "Erledigt"

        return entry_status

    @property
    def proper_time_format(self) -> tuple[str, str]:
        if self.start_of_entry and self.end_of_entry is not None:
            start = self.start_of_entry.strftime("%H" ":" "%M")
            end = self.end_of_entry.strftime("%H" ":" "%M")

        else:
            start, end = "", ""

        return start, end

    def __str__(self) -> str:
        return f"Tätigkeit: {self.entry_text}"

zeitplan/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from zeitplan.helper_functions import convert_str_to_datetime_date
from zeitplan.models import Day, EntryCategory, TimeEntry


def index(request) -> render:
    return render(request, "zeitplan/index.html")


def get_time_entry_list(day_id: int) -> dict:
    day = Day.objects.get(pk=day_id)

    time_entry_list = TimeEntry.objects.time_entry_for_a_day(day_id=day_id)

    context = {
        "day": day,
        "time_entry_list": time_entry_list,
    }

    return context


@login_required
def overview(request) -> render:
    all_days = Day.objects.all().order_by("day_date")
    context = {"all_days_list": all_days}

    return render(request, "zeitplan/overview.html", context)


@login_required
def day_overview(request, day_id: int) -> render:
    context = get_time_entry_list(day_id)

    return render(request, "zeitplan/day_overview.html", context)


@login_required
def day_edit(request, day_id: int) -> render:
    context = get_time_entry_list(day_id)

    return render(request, "zeitplan/day_editing.html", context)


@login_required
def day_editing(request, day_id: int) -> dict | HttpResponseRedirect:
    try:
        if "entry_vote" in request.POST:
            entries = Day.objects.get(pk=day_id).timeentry_set.get(
                pk=request.POST["entry_vote"]
            )
        elif "entry_passed" in request.POST:
            entries = Day.objects.get(pk=day_id).timeentry_set.get(
                pk=request.POST["entry_passed"]
            )
        elif "entry_delete" in request.POST:
            entries = Day.objects.get(pk=day_id).timeentry_set.get(
                pk=request.POST["entry_delete"]
            )

    except (KeyError, Day.DoesNotExist):
        context = {"day": Day.objects.get(pk=day_id), "error message": "Why?"}

        return render(request, "zeitplan/day_editing.html", context)

    else:
        if "entry_vote" in request.POST:
            entries.votes += 1
            entries.save()
        elif "entry_passed" in request.POST:
            if entries.entry_passed is None:
                entries.entry_passed = True
            else:
                entries.entry_passed = None
            entries.save()
        elif "entry_delete" in request.POST:
            entries.delete()

        return HttpResponseRedirect(
            reverse("zeitplan:day_edit", args=(Day.objects.get(pk=day_id).id,))
        )


@login_required
def category_add(request, entry_id: int) -> HttpResponseRedirect:
    entry = TimeEntry.objects.get(pk=entry_id)

    new_category = EntryCategory.objects.create_entry_category(
        category_text=request.POST["category_add"]
    )

    entry.entry_category = new_category
    entry.save()

    return HttpResponseRedirect(reverse("zeitplan:day_edit", args=(entry.day.id,)))


@login_required
def add_time_frame(request, entry_id: int) -> HttpResponseRedirect:
    entry = TimeEntry.objects.get(pk=entry_id)

    entry.start_of_entry = "%sT%s" % (
        entry.day.day_date,
        request.POST["add_time_frame_start"],
    )
    entry.end_of_entry = "%sT%s" % (
        entry.day.day_date,
        request.POST["add_time_frame_end"],
    )

    entry.save()

    return HttpResponseRedirect(reverse("zeitplan:day_edit", args=(entry.day.id,)))


@login_required
def day_new(request) -> render:
    return render(request, "zeitplan/day_new.html")


@login_required
def day_add_new(request):
    day_date_in_datetime_date = convert_str_to_datetime_date(request.POST["new_day"])

    new_day = Day.objects.create_day(
        day_date=day_date_in_datetime_date, user=request.user
    )

    return HttpResponseRedirect(reverse("zeitplan:overview"))


@login_required
def day_delete(request, day_id: int) -> HttpResponseRedirect:
    day_deleting = Day.objects.get(pk=day_id)
    day_deleting.delete()

    return HttpResponseRedirect(reverse("zeitplan:overview"))


@login_required
def time_entry_add(request, day_id: int) -> HttpResponseRedirect:
    new_entry = TimeEntry.objects.create_time_entry(
        day=Day.objects.get(pk=day_id),
        entry_text=request.POST["entry_add"],
        user=request.user,
    )

    return HttpResponseRedirect(reverse("zeitplan:day_edit", args=(new_entry.day.id,)))

zeitplan/templates/base.html
{% load static %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load django_htmx %}
<html>
    <head>
        <title>Zeitplan App</title>
    </head>
    <body>
        <link rel="stylesheet" href="{% static 'zeitplan/style.css' %}">
        {% block content %}{% endblock %}
        {% if not user.is_authenticated %}
            <a href="{% url 'login' %}">{{ "Login!" }}</a>
            <br />
        {% endif %}
        {% if user.is_authenticated %}
            <a href="{% url 'logout' %}">{{ "Logout!" }}</a>
        {% endif %}
    </body>
</html>

zeitplan/templates/zeitplan/day_editing.html
{% extends "base.html" %}
{% block content %}
    <ul>
        <h1>{{ day.day_name }} {{ day.different_day_date }}</h1>
        {% if error_message %}
            <p>
                <strong>{{ error_message }}</strong>
            </p>
        {% endif %}
        {% for entry in time_entry_list %}
            <li>
                <b>{{ "Tätigkeit:" }} {{ entry.entry_text }}
                    <br>
                </b>
            </li>
            <form action ="{% url 'zeitplan:add_time_frame' entry.id %}" method="post">
                {% csrf_token %}
                {{ "Startzeit:" }} {{ entry.proper_time_format.0 }}
                <input type="time"
                       name="add_time_frame_start"
                       id="add_time_frame_start{{ forloop.counter }}">
                <label for="add_time_frame{{ forloop.counter }}"></label>
                <br>
                {{ "Endzeit:" }} {{ entry.proper_time_format.1 }}
                <input type="time"
                       name="add_time_frame_end"
                       id="add_time_frame_end{{ forloop.counter }}">
                <label for="add_time_frame{{ forloop.counter }}"></label>
                <br>
                <input type="submit" value="Zeit speichern">
                <br>
            </form>
            <form action="{% url 'zeitplan:day_editing' day.id %}" method="post">
                {% csrf_token %}
                <input type="checkbox"
                       name="entry_vote"
                       id="entry_vote{{ forloop.counter }}"
                       value="{{ entry.id }}">
                <label for="entry_vote{{ forloop.counter }}">{{ "Aktuelle Stimmanzahl:" }} {{ entry.votes }}</label>
                <br>
                <input type="submit" value="Abstimmen">
                <br>
                <input type="checkbox"
                       name="entry_passed"
                       id="entry_passed{{ forloop.counter }}"
                       value="{{ entry.id }}">
                <label for="entry_passed{{ forloop.counter }}">{{ "Schon erledigt?" }} {{ entry.entry_status }}</label>
                <br>
                <input type="submit" value="Status ändern">
                <br>
                <input type="checkbox"
                       name="entry_delete"
                       id="entry_delete{{ forloop.counter }}"
                       value="{{ entry.id }}">
                <label for="entry_delete{{ forloop.counter }}">{{ "Tätigkeit entfernen?" }}</label>
                <br>
                <input type="submit" value="Tag entfernen">
            </form>
            <form action="{% url 'zeitplan:category_add' entry.id %}" method="post">
                {% csrf_token %}
                {{ "Aktuelle Kategorie:" }} {{ entry.entry_category.category_text }}
                <br>
                {{ "Kategorie ändern" }}
                <input type="text"
                       name="category_add"
                       id="category_add{{ forloop.counter }}">
                <label for="category_add{{ forloop.counter }}"></label>
                <br>
                <input type="submit" value="Abstimmen">
                <br>
            </form>
        {% endfor %}
    </ul>
    <form action="{% url 'zeitplan:time_entry_add' day.id %}" method="post">
        {% csrf_token %}
        <ul>
            {% if error_message %}
                <p>
                    <strong>{{ error_message }}</strong>
                </p>
            {% endif %}
            <li>
                <b>{{ "Neue Tätigkeit anlegen:" }}
                    <br>
                </b>
            </li>
            {{ "Tätigkeit benennen: " }}
            <input type="text" name="entry_add" id="entry_add{{ forloop.counter }}">
            <label for="entry_add{{ forloop.counter }}"></label>
            <br>
            <input type="submit" value="Tätigkeit anlegen">
            <br>
        </ul>
    </form>
    <ul>
    </il><a href="{% url 'zeitplan:day_overview' day.id %}">{{ "Zurück zur Tagesübersicht." }}</a>
    <br>
    <a href="{% url 'zeitplan:overview' %}">{{ "Zurück zur Übersicht aller Tage." }}</a>
    <br>
</ul>
{% endblock %}

zeitplan/templates/zeitplan/day_new.html
{% extends "base.html" %}
{% block content %}
    <form action="{% url 'zeitplan:day_add_new' %}" method="post">
        {% csrf_token %}
        <ul>
            <h1>{{ "Lege einen neuen Tag an" }}</h1>
            <li>{{ "Datum eingeben" }}</li>
            <br>
            <input type="date"
                   name="new_day"
                   id="new_day{{ forloop.counter }}"
                   value="{ new_day }}">
            <input type="submit" value="Tag anlegen/speichern">
            <br>
        </br>
    </form>
    <a href="{% url 'zeitplan:overview' %}">{{ "Zurück zur Übersicht aller Tage." }}</a>
</ul>
{% endblock %}

zeitplan/templates/zeitplan/day_overview.html
{% extends "base.html" %}
{% block content %}
    <form action="{% url 'zeitplan:day_delete' day.id %}" method="post">
        {% csrf_token %}
        <ul>
            <h1>{{ day.day_name_german }} {{ day.different_day_date }}</h1>
            {% if time_entry_list %}
                {% for entry in time_entry_list %}
                    <li>
                        <b>{{ "Tätigkeit: " }} {{ entry.entry_text }}
                        </li>
                    </b>
                {{ "Startzeit:" }} {{ entry.proper_time_format.0 }}</time>
                <br>
                {{ "Endzeit:" }} {{ entry.proper_time_format.1 }}
                <br>
                {{ "Kategorie: " }} {{ entry.entry_category.category_text }}
                <br>
                {{ "Aktuelle Stimmenanzahl: " }} {{ entry.votes }}
                <br>
                {{ "Schon erledigt?" }} {{ entry.entry_status }}
                <br>
                <br>
            {% endfor %}
        {% else %}
            <p>Aktuell keine Einträge vorhanden</p>
        {% endif %}
        <li>
            <b>{{ "Tag entfernen?" }}</b>
        </li>
        <label for="day_delete{{ forloop.counter }}"></label>
        <br>
        <input type="submit" value="Tag entfernen">
        <br>
    </br>
</form>
<a href="{% url 'zeitplan:day_edit' day.id %}">{{ "Weiter um Einträge zu bearbeiten." }}</a>
<br>
<a href="{% url 'zeitplan:overview' %}">{{ "Zurück zur Übersicht aller Tage." }}</a>
<br>
</ul>
{% endblock %}

zeitplan/templates/zeitplan/index.html
{% extends "base.html" %}
{% block content %}
    <ul>
        <h1>{{ "App Zeitplan" }}</h1>
        <li>{{ "Erste App ... Testlauf ... Spaß" }}</li>
        <br>
    </ul>
{% endblock %}

zeitplan/templates/zeitplan/overview.html
{% extends "base.html" %}
{% block content %}
    {% if all_days_list %}
        <ul>
            <h1>{{ "Übersicht über alle Tage" }}</h1>
            {% for day in all_days_list %}
                <li>
                    <b>{{ day.day_name_german }}</b>
                </li>
                {{ day.different_day_date }}
                <br>
                <a href="{% url 'zeitplan:day_overview' day.id %}">{{ "Wähle diesen Tag aus." }}</a>
                <br>
            </br>
        {% endfor %}
    {% else %}
        <p>No days are available.</p>
    {% endif %}
    <a href="{% url 'zeitplan:day_new' %}">{{ "Neuen Tag anlegen." }}</a>
    <br>
</ul>
{% endblock %}